"""Factor regressions on monthly excess returns, with Newey-West (HAC) errors.

Closed-form OLS + a Bartlett-kernel HAC covariance (no statsmodels dependency;
`tests/fixtures/hac_reference.json` pins statsmodels' numbers, generated by
`tests/fixtures/gen_hac_reference.py`, and the tests also check an
independent loop implementation).

HAC lag rule. The default is `DEFAULT_HAC_LAGS = 6` months: a fixed half-year
window, the packet's choice for monthly data. The Newey-West (1994) plug-in
rule `floor(4 * (T/100) ** (2/9))` would give 4 at the T=173 these series
have. Six is defensible as robustness to longer-memory autocorrelation, not
"more conservative": more lags can raise a t-stat (value's alpha t rises with the
lag). Alpha's t-stat is also reported
at lags 0 (no correction), 4 (the plug-in rule), 6 and 12 so the reader can
see whether the conclusion depends on the choice (`LAG_SENSITIVITY`).

Covariance: `V = (X'X)^-1 S (X'X)^-1`, `S = sum_t e_t^2 x_t x_t' + sum_{l=1..L}
(1 - l/(L+1)) sum_t e_t e_{t-l} (x_t x_{t-l}' + x_{t-l} x_t')`, with NO
small-sample n/(n-k) factor (statsmodels' `cov_type="HAC"` default). P-values
use the normal distribution, as statsmodels does for HAC.

Units. Everything here is a monthly DECIMAL return. The dependent variable
is the series' return minus the factor library's `RF` (T-bill) for the same
month; "alpha" is the regression intercept, annualised two ways (monthly x12,
and geometric `(1 + a) ** 12 - 1`). The t-statistic belongs to the monthly
intercept and applies to both annualisations.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd
from scipy import stats

from quantlab.validation.metrics import MONTHS_PER_YEAR

DEFAULT_HAC_LAGS = 6  # pinned by tests/test_regression.py; rule in the module docstring
LAG_SENSITIVITY = (0, 4, 6, 12)
ROLLING_WINDOW = 36
CAPM_FACTORS = ("Mkt-RF",)
FF5_MOM_FACTORS = ("Mkt-RF", "SMB", "HML", "RMW", "CMA", "Mom")


@dataclass(frozen=True)
class OlsFit:
    """One OLS fit with an intercept as the FIRST coefficient."""

    names: tuple[str, ...]
    coef: np.ndarray
    se_ols: np.ndarray
    se_hac: np.ndarray
    r2: float
    adj_r2: float
    n: int
    hac_lags: int
    resid: np.ndarray


def hac_covariance(x: np.ndarray, resid: np.ndarray, lags: int) -> np.ndarray:
    """Newey-West covariance of the OLS coefficients (see module docstring).
    `lags=0` is White's heteroskedasticity-robust estimator."""
    n = x.shape[0]
    if lags < 0 or lags >= n:
        raise ValueError(f"lags must be in [0, n), got {lags} for n={n}")
    xtx_inv = np.linalg.inv(x.T @ x)
    u = x * resid[:, None]
    s = u.T @ u
    for lag in range(1, lags + 1):
        weight = 1.0 - lag / (lags + 1.0)
        gamma = u[lag:].T @ u[:-lag]
        s = s + weight * (gamma + gamma.T)
    return xtx_inv @ s @ xtx_inv


def ols(y: np.ndarray, factors: np.ndarray, names: tuple[str, ...], hac_lags: int) -> OlsFit:
    """OLS of `y` on `factors` (n x k, NO constant column) plus an intercept.
    Standard errors are returned both classical and HAC(`hac_lags`)."""
    y = np.asarray(y, dtype=float)
    factors = np.asarray(factors, dtype=float).reshape(len(y), -1)
    n, k = factors.shape
    if n <= k + 1:
        raise ValueError(f"need more than {k + 1} observations, got {n}")
    x = np.column_stack([np.ones(n), factors])
    coef, *_ = np.linalg.lstsq(x, y, rcond=None)
    resid = y - x @ coef
    dof = n - (k + 1)
    sigma2 = float(resid @ resid) / dof
    se_ols = np.sqrt(np.diag(sigma2 * np.linalg.inv(x.T @ x)))
    se_hac = np.sqrt(np.diag(hac_covariance(x, resid, hac_lags)))
    tss = float(((y - y.mean()) ** 2).sum())
    r2 = 1.0 - float(resid @ resid) / tss if tss > 0 else float("nan")
    adj_r2 = 1.0 - (1.0 - r2) * (n - 1) / dof
    return OlsFit(("alpha", *names), coef, se_ols, se_hac, r2, adj_r2, n, hac_lags, resid)


@dataclass(frozen=True)
class AlignmentInfo:
    """What alignment to the factor months did to the series."""

    n_returns: int
    n_used: int
    first_month: str
    last_month: str
    dropped_months: tuple[str, ...]  # series months with no (or NaN) factor data
    factor_months_outside_window: int  # factor rows the series does not cover

    @property
    def n_dropped(self) -> int:
        return self.n_returns - self.n_used


def to_month_periods(returns: pd.Series) -> pd.Series:
    """Re-index a month-end-dated return series by calendar month. The engine
    labels each monthly return with that month's last trading day, so the
    period IS the month the return was earned in. Duplicate months raise."""
    out = returns.copy()
    out.index = pd.PeriodIndex(pd.DatetimeIndex(returns.index), freq="M")
    if out.index.has_duplicates:
        raise ValueError("two return observations fall in the same calendar month")
    return out.astype(float)


def align_to_factors(
    returns: pd.Series, factors: pd.DataFrame, columns: tuple[str, ...]
) -> tuple[pd.Series, pd.DataFrame, pd.Series, AlignmentInfo]:
    """Inner-join a monthly return series with the factor months.

    Returns `(excess, X, rf, info)`: the series minus `RF`, the requested
    factor columns, the `RF` series, all on the months where every one of
    them exists, plus an `AlignmentInfo` counting what was lost. Months with
    a NaN in `RF` or a requested column are dropped and counted."""
    monthly = to_month_periods(returns)
    needed = [*columns, "RF"]
    joined = factors[needed].reindex(monthly.index)
    usable = joined.notna().all(axis=1) & monthly.notna()
    dropped = tuple(str(p) for p in monthly.index[~usable.to_numpy()])
    kept = monthly[usable]
    x = joined.loc[usable, list(columns)]
    rf = joined.loc[usable, "RF"]
    info = AlignmentInfo(
        n_returns=len(monthly),
        n_used=len(kept),
        first_month=str(kept.index[0]) if len(kept) else "",
        last_month=str(kept.index[-1]) if len(kept) else "",
        dropped_months=dropped,
        factor_months_outside_window=len(factors.index.difference(monthly.index)),
    )
    return kept - rf, x, rf, info


def _norm_p(t: float) -> float:
    return float(2.0 * stats.norm.sf(abs(t)))


def regression_summary(
    y: pd.Series, x: pd.DataFrame, hac_lags: int = DEFAULT_HAC_LAGS
) -> dict[str, Any]:
    """Fit and report one regression as a JSON-ready dict. `y` and `x` must
    share an index (`align_to_factors` guarantees it)."""
    names = tuple(x.columns)
    fit = ols(y.to_numpy(), x.to_numpy(), names, hac_lags)
    t_hac = fit.coef / fit.se_hac
    t_ols = fit.coef / fit.se_ols
    alpha = float(fit.coef[0])
    alpha_t_by_lag: dict[str, float] = {}
    for lag in LAG_SENSITIVITY:
        if lag < fit.n:
            alt = ols(y.to_numpy(), x.to_numpy(), names, lag)
            alpha_t_by_lag[str(lag)] = float(alt.coef[0] / alt.se_hac[0])
    return {
        "n": fit.n,
        "hac_lags": hac_lags,
        "alpha_monthly": alpha,
        "alpha_annualised_arithmetic": alpha * MONTHS_PER_YEAR,
        "alpha_annualised_geometric": float((1.0 + alpha) ** MONTHS_PER_YEAR - 1.0),
        "alpha_se_annualised_hac": float(fit.se_hac[0] * MONTHS_PER_YEAR),
        "alpha_ci95_annualised_hac": [
            float((alpha - 1.96 * fit.se_hac[0]) * MONTHS_PER_YEAR),
            float((alpha + 1.96 * fit.se_hac[0]) * MONTHS_PER_YEAR),
        ],
        "alpha_t_hac": float(t_hac[0]),
        "alpha_t_ols": float(t_ols[0]),
        "alpha_p_hac_normal": _norm_p(float(t_hac[0])),
        "alpha_t_hac_by_lag": alpha_t_by_lag,
        "loadings": {
            name: {
                "coef": float(fit.coef[i + 1]),
                "se_hac": float(fit.se_hac[i + 1]),
                "t_hac": float(t_hac[i + 1]),
                "t_ols": float(t_ols[i + 1]),
            }
            for i, name in enumerate(names)
        },
        "r2": fit.r2,
        "adj_r2": fit.adj_r2,
        "idiosyncratic_variance_share": 1.0 - fit.r2,
    }


def rolling_capm(y: pd.Series, mkt: pd.Series, window: int = ROLLING_WINDOW) -> pd.DataFrame:
    """Rolling-window CAPM beta and R-squared of excess returns `y` on excess
    market returns `mkt`: one row per month once `window` months exist
    (the row is labelled by the window's LAST month)."""
    if len(y) < window:
        return pd.DataFrame(columns=["beta", "r2"], index=y.index[:0], dtype=float)
    yv, mv = y.to_numpy(), mkt.to_numpy()
    betas, r2s = [], []
    for end in range(window, len(y) + 1):
        ys, ms = yv[end - window : end], mv[end - window : end]
        var_m = ms.var(ddof=1)
        cov = np.cov(ys, ms, ddof=1)[0, 1]
        beta = cov / var_m
        corr2 = cov**2 / (var_m * ys.var(ddof=1)) if ys.var(ddof=1) > 0 else float("nan")
        betas.append(beta)
        r2s.append(corr2)
    return pd.DataFrame({"beta": betas, "r2": r2s}, index=y.index[window - 1 :])
