"""`AlpacaPaperBroker`: a `Broker` backed by Alpaca's paper-trading account
via `alpaca-py` (optional `[paper]` extra - `uv sync --extra paper`).

## No code path to a live endpoint

The constructor ALWAYS constructs `alpaca.trading.client.TradingClient` with
`paper=True`, then asserts the client's own resolved `_base_url` is
`BaseURL.TRADING_PAPER` (`alpaca.common.enums.BaseURL`) before returning -
raising `NotPaperAccountError` (core/errors.py) otherwise. This is
redundant with `paper=True` by construction today, but it is not vestigial:
it is the one place in this platform that would catch a FUTURE change to
`alpaca-py` (or a future edit to this file) that accidentally let a live
base URL through - see CLAUDE.md's "no live money" invariant and the work
packet's "there is no code path to a live endpoint". Nothing in this class
ever passes `paper=False` or accepts a `url_override`.

## Credentials

Read ONLY from `ALPACA_API_KEY`/`ALPACA_SECRET_KEY` environment variables
(CLAUDE.md - never in code or config). Missing either raises `BrokerError`
at construction, before any network call is attempted.

## Idempotency

`client_order_id` is generated by `paper/rebalancer.py` via
`paper.broker.client_order_id_for` (`f"{strategy_id[:12]}-{asof:%Y%m%d}-
{ticker}"` - work packet's own scheme, shared platform-wide - see
`broker.py`'s module docstring). Alpaca itself rejects a `submit_order` call
reusing a `client_order_id` it has already accepted (a 422/`APIError`); this
class catches exactly that case and replays the ALREADY-KNOWN outcome
(queried via `get_orders`, filtered by `client_order_id`) instead of
treating it as a failure - see `_submit_one`.

## Network tests

Every test touching this class's `submit`/`account`/`open_orders`/`cancel`/
`is_market_open` is `@pytest.mark.network` and skips cleanly without
`ALPACA_API_KEY`/`ALPACA_SECRET_KEY` (see tests/test_broker_contract.py).
The paper-endpoint assertion itself is a pure, offline unit test (no network
call is needed to check which URL a constructed client resolved to)."""

from __future__ import annotations

import os

import pandas as pd

from quantlab.core.errors import BrokerError, NotPaperAccountError
from quantlab.core.types import Fill, Order, OrderType, Position, Side, normalize_timestamp
from quantlab.paper.broker import (
    AccountSnapshot,
    Broker,
    BrokerCapabilities,
    OrderAck,
    OrderAckStatus,
)


class AlpacaPaperBroker(Broker):
    """See module docstring. `capabilities()` reports Alpaca's own paper
    account defaults (fractional shares yes, shorting yes on a margin
    account, no extended hours by default, $1 minimum notional) - a real
    account's actual permissions can differ; this is a reasonable, documented
    default, not a live query of `TradingClient.get_account()`'s options
    fields (out of scope for this milestone)."""

    def __init__(self) -> None:
        api_key = os.environ.get("ALPACA_API_KEY")
        secret_key = os.environ.get("ALPACA_SECRET_KEY")
        if not api_key or not secret_key:
            raise BrokerError(
                "AlpacaPaperBroker requires ALPACA_API_KEY and ALPACA_SECRET_KEY environment "
                "variables (CLAUDE.md: credentials never in code or config) - neither is read "
                "from anywhere else."
            )

        from alpaca.common.enums import BaseURL
        from alpaca.trading.client import TradingClient

        client = TradingClient(api_key=api_key, secret_key=secret_key, paper=True)
        if client._base_url != BaseURL.TRADING_PAPER:  # noqa: SLF001 - see module docstring
            raise NotPaperAccountError(
                f"AlpacaPaperBroker resolved a non-paper endpoint ({client._base_url!r}) - "  # noqa: SLF001
                "refusing to construct a client that could reach a live account. This should "
                "be unreachable given paper=True is always passed; treat this as a bug in "
                "alpaca-py or this class, not a configuration error to work around."
            )
        self._client = client

    def capabilities(self) -> BrokerCapabilities:
        return BrokerCapabilities(
            fractional_shares=True,
            shorting=True,
            extended_hours=False,
            min_order_notional=1.0,
        )

    def account(self) -> AccountSnapshot:
        acct = self._client.get_account()
        positions = self._client.get_all_positions()
        return AccountSnapshot(
            cash=float(acct.cash),
            equity=float(acct.equity),
            positions={
                p.symbol: Position(
                    ticker=p.symbol,
                    qty=float(p.qty) * (1 if str(p.side).lower().endswith("long") else -1),
                    avg_cost=float(p.avg_entry_price),
                )
                for p in positions
            },
        )

    def submit(self, orders: list[Order]) -> list[Fill | OrderAck]:
        return [self._submit_one(order) for order in orders]

    def _submit_one(self, order: Order) -> Fill | OrderAck:
        from alpaca.common.exceptions import APIError
        from alpaca.trading.enums import OrderSide, TimeInForce
        from alpaca.trading.requests import MarketOrderRequest

        request = MarketOrderRequest(
            symbol=order.ticker,
            qty=order.qty,
            side=OrderSide.BUY if order.side == Side.BUY else OrderSide.SELL,
            time_in_force=TimeInForce.DAY,
            client_order_id=order.client_order_id,
        )
        try:
            result = self._client.submit_order(request)
        except APIError as exc:
            if "client_order_id" in str(exc).lower() and "already" in str(exc).lower():
                # Idempotent resubmit (module docstring): replay the
                # already-known outcome rather than failing.
                existing = self._find_order_by_client_id(order.client_order_id)
                if existing is not None:
                    return self._order_to_ack_or_fill(existing, duplicate=True)
            return OrderAck(order.client_order_id, order.ticker, OrderAckStatus.REJECTED, str(exc))
        return self._order_to_ack_or_fill(result, duplicate=False)

    def _find_order_by_client_id(self, client_order_id: str):
        for o in self._client.get_orders():
            if o.client_order_id == client_order_id:
                return o
        return None

    def _order_to_ack_or_fill(self, order, *, duplicate: bool) -> Fill | OrderAck:
        from alpaca.trading.enums import OrderStatus

        # quant-gate VERDICT.md M08 cycle-1 finding 4: a DUPLICATE resubmit
        # ALWAYS surfaces as an OrderAck, even if Alpaca's own order is
        # (partially) filled - a caller must be able to tell "this run
        # genuinely executed a trade" from "this run asked again about an
        # order already settled on a prior run" (mirrors MockBroker.submit's
        # identical fix).
        if duplicate:
            return OrderAck(
                order.client_order_id, order.symbol, OrderAckStatus.DUPLICATE, str(order.status)
            )

        filled_qty = float(order.filled_qty or 0)
        if order.status in (OrderStatus.FILLED, OrderStatus.PARTIALLY_FILLED) and filled_qty > 0:
            fill_date = order.filled_at or order.submitted_at or pd.Timestamp.now("UTC")
            return Fill(
                client_order_id=order.client_order_id,
                ticker=order.symbol,
                qty=filled_qty,
                price=float(order.filled_avg_price or 0.0),
                date=normalize_timestamp(fill_date),
                commission=0.0,
            )
        status = (
            OrderAckStatus.REJECTED
            if order.status == OrderStatus.REJECTED
            else OrderAckStatus.ACCEPTED
        )
        return OrderAck(order.client_order_id, order.symbol, status, str(order.status))

    def open_orders(self) -> list[Order]:
        from alpaca.trading.enums import OrderSide, OrderStatus
        from alpaca.trading.requests import GetOrdersRequest

        raw = self._client.get_orders(filter=GetOrdersRequest(status=OrderStatus.OPEN))
        return [
            Order(
                client_order_id=o.client_order_id,
                ticker=o.symbol,
                side=Side.BUY if o.side == OrderSide.BUY else Side.SELL,
                qty=float(o.qty) - float(o.filled_qty or 0),
                order_type=OrderType.LIMIT
                if str(o.order_type).lower() == "limit"
                else OrderType.MARKET,
            )
            for o in raw
            if (float(o.qty) - float(o.filled_qty or 0)) > 0
        ]

    def cancel(self, client_order_id: str) -> None:
        existing = self._find_order_by_client_id(client_order_id)
        if existing is None:
            return
        self._client.cancel_order_by_id(existing.id)

    def is_market_open(self, asof: object) -> bool:
        from quantlab.core.calendar import is_trading_day

        return is_trading_day(asof)
